-- DANSCENTS MAXIMUM SECURITY SUPABASE SCHEMA & RLS POLICIES
-- Run this script in your Supabase SQL Editor:
-- https://supabase.com/dashboard/project/jtxelkzipsukuaorxbxt/sql

-- 1. Create Products Table
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  house TEXT NOT NULL,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  price NUMERIC NOT NULL,
  img TEXT DEFAULT '',
  notes TEXT DEFAULT '',
  tag TEXT DEFAULT '',
  stock INT DEFAULT 100,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Orders Table (Customer Orders)
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number TEXT UNIQUE NOT NULL,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  delivery_address TEXT NOT NULL,
  subtotal NUMERIC NOT NULL,
  shipping_fee NUMERIC NOT NULL,
  grand_total NUMERIC NOT NULL,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Order Items Table
CREATE TABLE IF NOT EXISTS public.order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.products(id),
  product_name TEXT NOT NULL,
  size TEXT NOT NULL,
  quantity INT NOT NULL,
  unit_price NUMERIC NOT NULL
);

-- 4. Create Bookings Table (Visit Reservations)
CREATE TABLE IF NOT EXISTS public.bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_reference TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  visit_date TEXT NOT NULL,
  visit_time TEXT NOT NULL,
  fragrance_notes TEXT DEFAULT '',
  status TEXT DEFAULT 'confirmed',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==================== MAXIMUM SECURITY RLS POLICIES ====================

-- Enable Row Level Security (RLS) on all tables
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

-- Drop old policies if existing to avoid conflicts
DROP POLICY IF EXISTS "Public Read Products" ON public.products;
DROP POLICY IF EXISTS "Deny Public Access Orders" ON public.orders;
DROP POLICY IF EXISTS "Deny Public Access Order Items" ON public.order_items;
DROP POLICY IF EXISTS "Deny Public Access Bookings" ON public.bookings;

-- 1. PRODUCTS: Allow public read-only catalog access
CREATE POLICY "Public Read Products" ON public.products FOR SELECT USING (true);

-- 2. ORDERS & ORDER ITEMS: Deny all direct public read/update/delete requests.
-- Orders can only be processed server-side through Vercel Serverless Functions using the Service Role Key!
-- No user can query or list another customer's orders via browser or API key.

-- 3. BOOKINGS: Deny all direct public read/update/delete requests.
-- Reservations can only be queried by store management on the backend.
